import "./globals.css";
import { Inter } from "next/font/google";
import Menu from "./components/Menu";
import PageAnimation from "./components/PageAnimation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  

 

  return (
    <html lang="en">
      <body
        className={`md:inline-grid mainGrid gap-4 max-md:p-4 p-8 ${inter.className}`}
      >
        <div>
          <Menu/>
        </div>
        <PageAnimation>
        {children}
        </PageAnimation>
      </body>
    </html>
  );
}
